default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: webb_app_development

test:
  <<: *default
  database: webb_app_test

production:
  <<: *default
  database: webb_app_production
